executable = /usr/bin/unbuffer
arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/featimp_dp/code/featimp_test.py --dataset $(dataset) --lr $(lr) --epochs $(epochs) --mini_batch_size $(mini_batch_size)
#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/featimp_dp/code/featimp_test.py --dataset $(dataset) --lr $(lr) --epochs $(epochs) --mini_batch_size $(mini_batch_size) --samples $(samples) --alpha $(alpha)



#var=switch_featimp_$(dataset)_$(samples)_$(alpha)_$(epochs)
var=switch_$(dataset)_lr_$(lr)_epochs_$(epochs)_mini_batch_size_$(mini_batch_size)

error = clust/clust_err/$(var).$(Process).err
output = clust/clust_out/point_nokl_real/$(var).$(Process).out
log = clust/clust_log/$(var).$(Process).log
#requirements = TARGET.CUDAGlobalMemoryMb > 30000
#buffer_size = 1000
#stream_output=True
request_memory = 8040
request_cpus = 1
#request_gpus = 1

+MaxRunningPrice = 10000
+RunningPriceExceededAction = "kill"

#queue dataset,epochs,lr,mini_batch_size from /home/kadamczewski/Dropbox_from/Current_research/featimp_dp/parameters2.txt
queue dataset,lr,epochs,mini_batch_size from /home/kadamczewski/Dropbox_from/Current_research/featimp_dp/parameters2.txt
#queue dataset,lr,epochs,num_Dir_samples from /home/kadamczewski/Dropbox_from/Current_research/featimp_dp/parameters.txt




# dataset = orange_skin
# samples=50
# alpha=0.5
# epochs=10
# queue 1

#dataset=intrusion
#queue 1




