#!/bin/bash
python3.7 main_invase.py --seed 1 --data_type XOR
python3.7 main_invase.py --seed 2 --data_type XOR
python3.7 main_invase.py --seed 3 --data_type XOR
python3.7 main_invase.py --seed 4 --data_type XOR
python3.7 main_invase.py --seed 5 --data_type XOR
python3.7 main_invase.py --seed 1 --data_type orange_skin
python3.7 main_invase.py --seed 2 --data_type orange_skin
python3.7 main_invase.py --seed 3 --data_type orange_skin
python3.7 main_invase.py --seed 4 --data_type orange_skin
python3.7 main_invase.py --seed 5 --data_type orange_skin
python3.7 main_invase.py --seed 1 --data_type nonlinear_additive
python3.7 main_invase.py --seed 2 --data_type nonlinear_additive
python3.7 main_invase.py --seed 3 --data_type nonlinear_additive
python3.7 main_invase.py --seed 4 --data_type nonlinear_additive
python3.7 main_invase.py --seed 5 --data_type nonlinear_additive
python3.7 main_invase.py --seed 1 --data_type syn4
python3.7 main_invase.py --seed 2 --data_type syn4
python3.7 main_invase.py --seed 3 --data_type syn4
python3.7 main_invase.py --seed 4 --data_type syn4
python3.7 main_invase.py --seed 5 --data_type syn4
python3.7 main_invase.py --seed 1 --data_type syn5
python3.7 main_invase.py --seed 2 --data_type syn5
python3.7 main_invase.py --seed 3 --data_type syn5
python3.7 main_invase.py --seed 4 --data_type syn5
python3.7 main_invase.py --seed 5 --data_type syn5
python3.7 main_invase.py --seed 1 --data_type syn6
python3.7 main_invase.py --seed 2 --data_type syn6
python3.7 main_invase.py --seed 3 --data_type syn6
python3.7 main_invase.py --seed 4 --data_type syn6
python3.7 main_invase.py --seed 5 --data_type syn6
