---
xor:
  point_estimate: 0
  switch_nn: 1
  kl_term: 1
  alpha: 0.01
  batch: 200
  epochs: 5
  lr: 0.01
  num_Dir_samples: 200

subtract:
  point_estimate: 0
  switch_nn: 1
  kl_term: 1
  alpha: 0.0001
  batch: 50
  epochs: 3
  lr: 0.01
  num_Dir_samples: 500

#orange_skin:
#  point_estimate: 0
#  switch_nn: 1
#  kl_term: 1
#  alpha: 0.01
#  batch: 200
#  epochs: 5
#  lr: 0.001
#  num_Dir_samples: 500

orange_skin:
  point_estimate: 1
  switch_nn: 0
  kl_term: 0
  alpha: 0.01
  batch: 200
  epochs: 10
  lr: 0.01

nonlinear_additive:
  point_estimate: 0
  switch_nn: 1
  kl_term: 1
  alpha: 0.001
  batch: 100
  epochs: 10
  lr: 0.05
  num_Dir_samples: 500

nonliear_additive_tentative:
  point_estimate: 0
  switch_nn: 1
  kl_term: 1
  alpha: 1.0
  batch: 100
  epochs: 10
  lr: 0.05
  num_Dir_samples: 500

...